const SEARCH_MOVIES_REQUEST = 'app/search/SEARCH_MOVIES_REQUEST'
const SEARCH_MOVIES_FAILURE = 'app/search/SEARCH_MOVIES_FAILURE'
const SEARCH_MOVIES_SUCCESS = 'app/search/SEARCH_MOVIES_SUCCESS'

const CLEAR_SEARCH_RESULTS = 'app/search/CLEAR_SEARCH_RESULTS'

export default {
    SEARCH_MOVIES_REQUEST,
    SEARCH_MOVIES_FAILURE,
    SEARCH_MOVIES_SUCCESS,
    CLEAR_SEARCH_RESULTS
}